name: mobile_front_end
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue: ^0.8.0
  device_info: ^2.0.3
  flutter_nearby_connections: ^1.1.2
  flutter_styled_toast: ^2.2.1
  http: ^1.2.0
  uuid: ^4.3.3
  nearby_connections: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
